server:
  port: 8080
  error:
    include-stacktrace: never
  servlet:
    context-path: /azsim

spring:
  data:
    mongodb:
      uri: mongodb://root:admin@localhost:27017/dhxqhp_azsimdb?authSource=admin
  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    ROOT: INFO