server:
  port: 9000
  error:
    include-stacktrace: never
  servlet:
    context-path: /

spring:
  data:
    mongodb:
      uri: mongodb://${USER_DB}:${PASS_DB}@${HOST_DB}:27017/${DATABASE_DB}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    ROOT: INFO


