server:
  error:
    include-stacktrace: never
  servlet:
    context-path: /api
spring:
  data:
    mongodb:
      uri: mongodb://${user_db}:${pass_db}@${host_db}:27017/${database_db}

logging:
  level:
    ROOT: INFO