# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

  build-frontend:
    runs-on: ubuntu-latest
    needs: [checkout]

    steps:
      - name: Build React
        run: ls -la && cd react && npm install -g vite && npm install && vite build --base=/azsim/

  build-backend:
    runs-on: ubuntu-latest
    needs: [build-frontend]

    steps:
      - name: Build Java
        run: mvn -P release -B package --file pom.xml

  undeploy:
    runs-on: ubuntu-latest
    needs: [build-backend]

    steps:
      - name: Undeploy Tomcat
        shell: bash
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          curl -v -u "$TOMCAT_USER:$TOMCAT_PASSWORD" "http://www.application.dev.br/manager/text/undeploy?path=/azsim"

  deploy:
    runs-on: ubuntu-latest
    needs: [undeploy]

    steps:
      - name: Deploy Tomcat
        shell: bash
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
        run: |
          curl -v -u "$TOMCAT_USER:$TOMCAT_PASSWORD" -T target/azsim.war "http://www.application.dev.br/manager/text/deploy?path=/azsim"
