# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build React
      run: cd react && npm install -g vite && npm install && vite build --base=/azsim/

    - name: Build Java
      run: mvn -P release -B package --file pom.xml

    - name: Undeploy Tomcat
      shell: bash
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        curl -v -u "$TOMCAT_USER:$TOMCAT_PASSWORD" "http://www.application.dev.br/manager/text/undeploy?path=/azsim"

    - name: Deploy Tomcat
      shell: bash
      env:
        TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        curl -v -u "$TOMCAT_USER:$TOMCAT_PASSWORD" -T target/azsim.war "http://www.application.dev.br/manager/text/deploy?path=/azsim"
